language : node_js

notifications :
    email :
        on_success : never
        on_failure : always

node_js : 
  - stable

after_success :
  - cat ./build/reports/coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
